import { createPattern } from 'redux-router'

export const Homepage = createPattern('/')
export const JobOverview = createPattern('/ons-klusaanbod')
export const Premium = createPattern('/onze-abonnementen')
export const EmergencyJob = createPattern('/spoedgevallen')
export const Colofon = createPattern('/colofon')
export const Faq = createPattern('/faq')
export const Contact = createPattern('/contact')
export const ContactConfirmation = createPattern('/contact-confirmation')
export const CategoryOverviewPage = createPattern('/category-overview')
export const LoginPage = createPattern('/login')
export const CreateAccountPage = createPattern('/create-account')
export const CreateAccountConfirmationPage = createPattern('/create-account/confirmation')
export const ForgotPasswordPage = createPattern('/forgot-password')
export const ForgotPasswordConfirmationPage = createPattern('/forgot-password/confirmation')
export const ResetPasswordPage = createPattern('/reset-password')
export const ResetPasswordConfirmationPage = createPattern('/reset-password/confirmation')
export const CategoryDetailPage = createPattern('/category/:IdJobCategory/:Name(/:IdJob/:JobName)')
export const VerifyAccountPage = createPattern('/verify-account')

export const DashboardOverview = createPattern('/mijn-zoopgelost(/overzicht)')
export const DashboardOverviewDetail = createPattern('/mijn-zoopgelost/order/:IdOrder')
export const DashboardPayment = createPattern('/mijn-zoopgelost/betaal-gegevens')
export const DashboardPremium = createPattern('/mijn-zoopgelost/premium')
export const DashboardProfile = createPattern('/mijn-zoopgelost/profiel')
export const DashboardLogout = createPattern('/mijn-zoopgelost/logout')
export const DashboardNotFound = createPattern('/mijn-zoopgelost(/*)')

export const OrderImage = createPattern('/orders/:IdOrder/photos/:IdPhoto')
export const OrderInvoice = createPattern('/orders/:IdOrder/invoice')

export const TermsPremium = createPattern('/assets/files/ZoOpgelost_abonnements-en-actievoorwaarden.pdf')
export const TermsService = createPattern('/assets/files/ZoOpgelost_dienstenvoorwaarden-MainPlus.pdf')
